config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis
  resources :collaborators, only: [:create, :destroy] do
    collection do
      get "search"
    end
  end

  get 'users/upgrade'

  resources :users do
    collection do
      get "upgrade"
    end
    post "toggle_role"
    post "go_standard"
  end

  resources :charges, only: [:new, :create]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_presence_of :name, :email
  validates :email, format: /\b[a-zA-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b/

  has_many :collaborators
  has_many :collaborations, through: :collaborators, source: :wiki
  has_many :wikis


  after_initialize :init

  def self.search(search)
    search_condition = "%" + search + "%"
    where('name LIKE ? OR email LIKE ?', search_condition, search_condition)
  end

  def admin?
    role == 'admin'
  end

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def init
    self.role ||= 'standard'
  end

   def upgrade
    @user = current_user
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  default_scope {order('Title ASC')}
  scope :visible_to, -> (user) do
    if user.admin? || user.premium?
      all
    else
      where(private: nil)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    flash[:error] = "You are not authoried to make this changes to the wiki."
    redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Premium Blocipedia Membership - #{current_user.email}",
      amount: 10_00
    }
  end

  def create
    @amount = 10_00

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app)
      amount: @amount,
      description: "Premium Blocipedia Membership - #{current_user.email}",
      currency: 'usd'
      )

    current_user.update_attributes!( role: 'premium')

    flash[:success] = "Payment was successful, membership upgraded to Premium for  #{current_user.email}!"
    redirect_to root_path # or whereever

    # Stripe will send back CardErrors, with friendly messages when something goes wrong.
    # This 'rescue block' catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    @collaborator.save
    redirect_to edit_wiki_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def search
    @users = User.search(params[:search])
    @wiki_id = params[:wiki_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @wikis = @user.wikis
    @collaborators = @user.collaborators
    @wiki = Wiki.all
  end

  def toggle_role
    @user = current_user

    if @user.admin? == 'admin'
      flash[:error] = "User is an admin. No update."
    elsif @user.standard?
      @user.update_attribute(:role, 'premium')
      flash[:notice] = "User switced from from standard to premium."
    else
      @user.update_attribute(:role, 'standard')
      flash[:notice] = "User switced from premium to standard."
    end
    redirect_to users_upgrade_path
  end

  def go_premium
    @user = current_user
    @user.update_attribute(:role, 'premium')
  end

  def go_standard
    @user = current_user
    @user.update_attribute(:role, 'standard')
    flash[:notice] = "User switched from premium to standard."
    redirect_to edit_user_registration_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis =  policy_scope(Wiki.all.paginate(page: params[:page], per_page: 10))
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Wiki has been saved."
      redirect_to @wiki
    else
      flash[:notice] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])

    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki has been updated."
      redirect_to wiki_path(@wiki)
    else
      flash[:error] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    title = @wiki.title
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="center3">
  <div class="col-md-6 col-md-offset-3">
    <h3> Upgrade your membership today!</h3>
      <h5>The added Benefits of Premium Members.</h5>
      <ul>
        <li>Choose if a Wiki is public or private.</li>
        <li>Add individual Collaborators to each private wiki</li>
        <li>Lifetime membership $10</li>
      </ul>
        <%= form_tag charges_path do %>
          <script class='stripe-button'
                  src="https://checkout.stripe.com/checkout.js"
                  data-key="<%= @stripe_btn_data[:key] %>"
                  data-amount=<%= @stripe_btn_data[:amount] %>
                  data-description=="<%= @stripe_btn_data[:description] %>" >
          </script>
        <% end %>
  </div>
</div>

app/views/collaborators/_collaborators.html.erb
<div class="display">
  <h2>Add Collaborators</h2>
</div>

<div class="space">
  <% if @wiki.user == current_user %>

    <%= simple_form_for collaborators_path, method: :post do %>
      <%= text_field_tag :email %>
      <%= hidden_field_tag :wiki_id, @wiki.id %>
      <%= submit_tag "Add Collaborator",class: "btn btn-success"%>
    <% end %>
  <% end %>

  <h2>Wiki Collaborators</h2>
  <% @wiki.collaborators.each do |collaborator| %>
    <p class="lead">
      <%= collaborator.user.email %>
      <% if @wiki.user == current_user %>
        <%= link_to "", [collaborator], method: :delete, class: 'glyphicon glyphicon-trash' %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/collaborators/search.html.erb
<div class="container">
  <table>
    <caption><h1>Collaborators</h1></caption>
      <tr>
        <th>User</th>
        <th>Email</th>
        <th>Add</th>
      </tr>
        <% @users.each do |user| %>
      <tr>
        <td class="left"><h3><%=user.name %></h3></td>
        <td class="middle"><h3><%=user.email %></h3></td>
        <%= form_tag collaborators_path, method: :post do %>
          <%= hidden_field_tag :wiki_id, @wiki_id %>
          <%= hidden_field_tag :user_id, user.id %>
        <td class="right-side"><%= submit_tag "Add Collaborator",class: "btn btn-success"%></td>

         <% end %>
      </tr>
        <% end %>
  </table>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer", class= "navbar-fixed-bottom">
  <div class="container ">
    <div class="row">

    </div><!--/row-->
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Blocipedia</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <% if current_user && current_user.role == 'standard' %>
          <li><%= link_to "Update", new_charge_path %></li>
        <% end %>
      </ul>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <div class="user-info">
          <% if current_user %>
            Hello <%= link_to (current_user.name || current_user.email), current_user %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-info btn-sm' do %>
              <span class= "glyphicon glyphicon-user"></span>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm' do  %>
              <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
        </div>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
      </ul>
          <% end %>
        </div>
    </div>
  </div>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", content: ENV['STRIPE_PUBLIC_KEY'] %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container-fluid">
<%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/users/search.html.erb
<% @users.each do |user| %>
  <div><%=user.name %></div>
  <div><%=user.email %></div>
<% end %>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="display">
    <h1><%= @user.name %>'s Wikis</h1>
  </div>
  <div class="new-tab">
    <%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
  </div>
  <div class="my-wiki">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-headings">
            <%= link_to wiki.title, wiki %>
            <div class="right">
              <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success' %>
              <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger' %>
            </div>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="co-wiki">
    <h2>Collaborator Wiki</h2>
    <% @collaborators.each do |collaborator| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-headings">
            <%# if collaborator.user_id == current_user.id %>
              <%= link_to collaborator.wiki.title %>
            <%# end %>
            <div class="right">
              <%#= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success' %>
            </div>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/upgrade.html.erb
<h1>Upgrade your account now!</h1>
<p>Current Role: <%= current_user.role %></p>
<p>Click here to toggle your role. <%= button_to "Toggle", user_toggle_role_path(current_user), method: :post, class: 'btn btn-success' %></p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="section1">
  <h1>Blocipedia:  Social, Markdown Wikis</h1>
  <h3>The Benefits of Wikis?</h3>
  <div class="row">
    <div class="col-md-4">
      <i class="fa fa-sitemap fa-5x circle"></i>
      <p class="lead"> <strong>Organization</strong></p>
      <p class="lead"> Wikis allow you to keep all of your thoughts and information in one location by allowing you to edit and update at any time.
    </div>

    <div class="col-md-4">
      <i class="fa fa-rocket fa-5x circle"></i>
      <p class="lead"><strong>Speed</strong></p>
      <p class="lead">Wikis create a quick platform to create new Wikis, update old, or add to others all in one place. Saving you time and frustration.</p>
    </div>

    <div class="col-md-4">
      <i class="fa fa-user fa-5x circle"></i></span>
      <p class="lead"><strong>Colaberation</strong></p>
      <p class="lead">The most powerful part of a wiki is the ability for multiple people to contribute to it.  By allowing others to add to wikis you create an endless knowledge pool.</p>
    </div>
  </div>
</div>

<div class="section2">
  <h1>Start Creating Today!</h1>
  <h2>Standard membership is FREE and includes unlimited public wikis!</h2>
    <p><%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg btn-intro' %></p>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
     <%= f.field :body %>
     <%= f.hidden_field :body, id: "body" %>
    <div id="epiceditor"></div>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success', onclick: "prep()" %>
  </div>
<% end %>

 <script>
   var editor = new EpicEditor().load();
   editor.getElement('editor').body.innerHTML = '<%= escape_javascript(@wiki.body) %>';
   function prep() {
     $("#body")[0].value = (editor.getElement('editor').body.innerHTML);
   }
 </script>

app/views/wikis/_search.html.erb
<%= form_tag search_collaborators_path, method: :get do %>
  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
  <%= hidden_field_tag :wiki_id, @wiki.id %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-success" %>
<% end %>
<div class="row">
  <h2>Wiki Collaborators</h2>
    <% @wiki.collaborators.each do |collaborator| %>
      <p class="lead">
        <%= collaborator.user.name %>
        <% if @wiki.user == current_user %>
          <%= link_to "", [collaborator], method: :delete, class: 'glyphicon glyphicon-trash' %>
        <% end %>
      </p>
    <% end %>
</div>

app/views/wikis/edit.html.erb
<%= link_to @wiki do %>
  <i class="fa fa-arrow-circle-o-left"></i>
<% end %>

<div class="display">
  <h1>Edit Wiki</h1>
</div>

<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for @wiki do |f| %>
    <div class="form-inputs">
      <%= f.input :title, label: "Title", required: true, autofocus: true %>
      <%= f.input :body, label: "Wiki Body", required: true %>
        <% if current_user.role == 'premium' && current_user.id == @wiki.user_id %>
          <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
    </div>
  <% end %>
    <div class="form-actions">
      <%= f.button :submit, "Update Wiki", class: 'btn btn-success' %>
    </div>
  <% end %>

  <% if current_user.role == "premium"  && @wiki.user_id == current_user.id %>
    <%= render partial: "search", locals: { wiki: @wiki} %>
  <% end %>
</div>

app/views/wikis/index.html.erb
<h1> Wikis</h1>
<%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>
  <%= will_paginate @wikis %>

app/views/wikis/new.html.erb
<div class="display">
  <h1>Create New Wiki</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for @wiki do |f| %>
      <div class="form-inputs">
        <%= f.input :title, label: "Title", required: true, autofocus: true %>
        <%= f.input :body, label: "Wiki Body", required: true %>
          <% if current_user.role == 'premium' %>
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
      </div>
    <% end %>
      <div class="form-actions">
        <%= f.button :submit, "Publish Wiki", class: 'btn btn-success' %>
      </div>
    <% end %>
    <% if current_user.role == "premium" %>
      <%= render partial: "search", locals: { wiki: @wiki } %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<%= link_to wikis_path do%>
<i class="fa fa-arrow-circle-o-left"></i>
<% end %>
<% if policy(@wiki).show? %>
  <h1><%= markdown_to_html @wiki.title %></h1>
  <p><%= markdown_to_html @wiki.body %></p>
  <small>
    <i>author: <%= @wiki.user.name %></i>
  </small>
<% end %>
<br/>
<% if policy(@wiki).update? %>
  <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>
<% if current_user.id == @wiki.user_id %>
  <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger' %>
<% end %>